### ISSUE TITLE
circleci salesforce orb検証

### ISSUE THREAD

**Issue by hts-cuishj99** [hts-cuishj99/First_PJ#3]
## circleci for salesforce
https://circleci.com/developer/orbs/orb/circleci/salesforce-sfdx

- Usage Examples
create_open_delete_scratch

```
jobs:
  create-open-delete:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          defaultusername: user@email.com
      - sfdx/scratch-create:
          scratch-alias: circleci
          scratch-config: ./config/project-scratch-def.json
      - sfdx/scratch-open:
          scratch-alias: circleci
      - sfdx/scratch-delete:
          scratch-alias: circleci
orbs:
  sfdx: circleci/salesforce-sfdx@x.y
version: 2.1
workflows:
  basic-test:
    jobs:
      - create-open-delete

```

- install_and_authenticate
Simple example showing how to install the Salesforce sfdx CLI with the default options and authenticate against it with JWT.

```
jobs:
  install_authenticate:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          defaultusername: user@email.com
      - run:
          command: >
            echo You now have access to the sfdx cli and may execute commands
            against it.

            sfdx auth:list
          name: Run your SFDX commands here
orbs:
  sfdx: circleci/salesforce-sfdx@x.y
version: 2.1
workflows:
  basic-test:
    jobs:
      - install_authenticate
```
